[package]
name = "pdx-desktop"
version = "0.1.0"
description = ""
edition = "2024"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }
tauri = { workspace = true, features = ["macos-private-api"] }
tauri-plugin-log = { workspace = true }
eu5save = { workspace = true }
eu5app = { workspace = true, features = ["zstd_c", "game-install"] }
jomini = { workspace = true }
dirs = { workspace = true }
rayon = { workspace = true }
pdx-assets = { workspace = true }
pdx-map = { workspace = true, features = ["render", "interaction"] }
